library(SASxport)
ACQ<- read.xport("nnhanes0102/ACQ_B.XPT")
ALQ<- read.xport("nnhanes0102/ALQ_B.XPT")
AUQ<- read.xport("nnhanes0102/AUQ_B.XPT")
BAQ<- read.xport("nnhanes0102/BAQ_B.XPT")
BMX<- read.xport("nnhanes0102/BMX_B.XPT")
BPQ<- read.xport("nnhanes0102/BPQ_B.XPT")
BPX<- read.xport("nnhanes0102/BPX_B.XPT")
CIQDEP<- read.xport("nnhanes0102/CIQDEP_B.XPT")
CIQGAD<- read.xport("nnhanes0102/CIQGAD_B.XPT")
CDQ<- read.xport("nnhanes0102/CDQ_B.XPT")
CFQ<- read.xport("nnhanes0102/CFQ_B.XPT")
DBQ<- read.xport("nnhanes0102/DBQ_B.XPT")
DEMO<- read.xport("nnhanes0102/DEMO_B.XPT")
DEQ<- read.xport("nnhanes0102/DEQ_B.XPT")
DIQ<- read.xport("nnhanes0102/DIQ_B.XPT")
DSQ1 <- read.xport("nnhanes0102/DSQ1_B.XPT")
DSQ2 <- read.xport("nnhanes0102/DSQ2_B.XPT")
DUQ <- read.xport("nnhanes0102/DUQ_B.XPT")
ECQ <- read.xport("nnhanes0102/ECQ_B.XPT")
FSQ <- read.xport("nnhanes0102/FSQ_B.XPT")
HCQ <- read.xport("nnhanes0102/HCQ_B.XPT")
HIQ <- read.xport("nnhanes0102/HIQ_B.XPT")
HOQ <- read.xport("nnhanes0102/HOQ_B.XPT")
HSQ <- read.xport("nnhanes0102/HSQ_B.XPT")
HUQ <- read.xport("nnhanes0102/HUQ_B.XPT")
IMQ <- read.xport("nnhanes0102/IMQ_B.XPT")
KIQ <- read.xport("nnhanes0102/KIQ_U_B.XPT")
KIQP <- read.xport("nnhanes0102/KIQ_P_B.XPT")
MCQ <- read.xport("nnhanes0102/MCQ_B.XPT")
MPQ <- read.xport("nnhanes0102/MPQ_B.XPT")
OCQ <- read.xport("nnhanes0102/OCQ_B.XPT")
OHQ <- read.xport("nnhanes0102/OHQ_B.XPT")
OSQ <- read.xport("nnhanes0102/OSQ_B.XPT")
PAQ <- read.xport("nnhanes0102/PAQ_B.XPT")
PAQIAF <- read.xport("nnhanes0102/PAQIAF_B.XPT")
PFQ <- read.xport("nnhanes0102/PFQ_B.XPT")
PUQ <- read.xport("nnhanes0102/PUQ_B.XPT")
RDQ <- read.xport("nnhanes0102/RDQ_B.XPT")
RHQ <- read.xport("nnhanes0102/RHQ_B.XPT")
RXQANA <- read.xport("nnhanes0102/RXQANA_B.XPT")
SMQ <- read.xport("nnhanes0102/SMQ_B.XPT")
SMQFAM <- read.xport("nnhanes0102/SMQFAM_B.XPT")
SSQ <- read.xport("nnhanes0102/SSQ_B.XPT")
SXQ <- read.xport("nnhanes0102/SXQ_B.XPT")
VIQ <- read.xport("nnhanes0102/VIQ_B.XPT")
WHQ <- read.xport("nnhanes0102/WHQ_B.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE) ###doesn't exist for 07/08
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE) ###doesn't exist for 11/12
#AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE) ###doesn't exist for 03/04
#DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)  ###doesn't exist for 05/06
DtoP <- merge(DUQ, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE) ###doesn't exist for 11/12
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE) ####doesn't exist for 03/04
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE) ####doesn't exist for 09/10
#RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)  ####doesn't exist for 03/04
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE) ####doesn't exist for 03/04
#RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)  ####doesn't exist for 11/12
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)  ####doesn't exist for 03/04
final0102 <- RtoW
write.table(final0102, file="finalTables/finalTable0102.txt")
