library(SASxport)
ACQ<- read.xport("nnhanes1314/ACQ_H.XPT")
ALQ<- read.xport("nnhanes1314/ALQ_H.XPT")
BPQ<- read.xport("nnhanes1314/BPQ_H.XPT")
BMX<- read.xport("nnhanes1314/BMX_H.XPT")
BPX<- read.xport("nnhanes1314/BPX_H.XPT")
CBQ<- read.xport("nnhanes1314/CBQ_H.XPT")
CDQ<- read.xport("nnhanes1314/CDQ_H.XPT")
CFQ<- read.xport("nnhanes1314/CFQ_H.XPT")
CKQ<- read.xport("nnhanes1314/CKQ_H.XPT")
CSQ<- read.xport("nnhanes1314/CSQ_H.XPT")
DBQ<- read.xport("nnhanes1314/DBQ_H.XPT")
DEMO<- read.xport("nnhanes1314/DEMO_H.XPT")
DEQ<- read.xport("nnhanes1314/DEQ_H.XPT")
DIQ<- read.xport("nnhanes1314/DIQ_H.XPT")
DLQ<- read.xport("nnhanes1314/DLQ_H.XPT")
DPQ<- read.xport("nnhanes1314/DPQ_H.XPT")
DSQIDS <- read.xport("nnhanes1314/DSQIDS_H.XPT")
DSQTOT <- read.xport("nnhanes1314/DSQTOT_H.XPT")
DUQ <- read.xport("nnhanes1314/DUQ_H.XPT")
ECQ <- read.xport("nnhanes1314/ECQ_H.XPT")
FSQ <- read.xport("nnhanes1314/FSQ_H.XPT")
HEQ <- read.xport("nnhanes1314/HEQ_H.XPT")
HIQ <- read.xport("nnhanes1314/HIQ_H.XPT")
HOQ <- read.xport("nnhanes1314/HOQ_H.XPT")
HSQ <- read.xport("nnhanes1314/HSQ_H.XPT")
HUQ <- read.xport("nnhanes1314/HUQ_H.XPT")
IMQ <- read.xport("nnhanes1314/IMQ_H.XPT")
INQ <- read.xport("nnhanes1314/INQ_H.XPT")
KIQ <- read.xport("nnhanes1314/KIQ_U_H.XPT")
MCQ <- read.xport("nnhanes1314/MCQ_H.XPT")
OCQ <- read.xport("nnhanes1314/OCQ_H.XPT")
OHQ <- read.xport("nnhanes1314/OHQ_H.XPT")
OSQ <- read.xport("nnhanes1314/OSQ_H.XPT")
PAQ <- read.xport("nnhanes1314/PAQ_H.XPT")
PFQ <- read.xport("nnhanes1314/PFQ_H.XPT")
PUQMEC <- read.xport("nnhanes1314/PUQMEC_H.XPT")
RHQ <- read.xport("nnhanes1314/RHQ_H.XPT")
RXQASA <- read.xport("nnhanes1314/RXQASA_H.XPT")
SLQ <- read.xport("nnhanes1314/SLQ_H.XPT")
SMQ <- read.xport("nnhanes1314/SMQ_H.XPT")
SMQFAM <- read.xport("nnhanes1314/SMQFAM_H.XPT")
SMQRTU <- read.xport("nnhanes1314/SMQRTU_H.XPT")
SMQSHS <- read.xport("nnhanes1314/SMQSHS_H.XPT")
SXQ <- read.xport("nnhanes1314/SXQ_H.XPT")
VTQ <- read.xport("nnhanes1314/VTQ_H.XPT")
WHQ <- read.xport("nnhanes1314/WHQ_H.XPT")
WHQMEC <- read.xport("nnhanes1314/WHQMEC_H.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)
DtoP <- merge(DtoP, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final1314 <- RtoW
write.table(final1314, file="finalTables/finalTable1314.txt")
