library(SASxport)
ACQ<- read.xport("nnhanes1516/ACQ_I.XPT")
ALQ<- read.xport("nnhanes1516/ALQ_I.XPT")
AUQ<- read.xport("nnhanes1516/AUQ_I.XPT")
AUX<- read.xport("nnhanes1516/AUX_I.XPT")
BMX<- read.xport("nnhanes1516/BMX_I.XPT")
BPQ<- read.xport("nnhanes1516/BPQ_I.XPT")
BPX<- read.xport("nnhanes1516/BPX_I.XPT")
CBQ<- read.xport("nnhanes1516/CBQ_I.XPT")
CDQ<- read.xport("nnhanes1516/CDQ_I.XPT")
DBQ<- read.xport("nnhanes1516/DBQ_I.XPT")
DEMO<- read.xport("nnhanes1516/DEMO_I.XPT")
DEQ<- read.xport("nnhanes1516/DEQ_I.XPT")
DIQ<- read.xport("nnhanes1516/DIQ_I.XPT")
DLQ<- read.xport("nnhanes1516/DLQ_I.XPT")
DPQ<- read.xport("nnhanes1516/DPQ_I.XPT")
DSQIDS <- read.xport("nnhanes1516/DSQIDS_I.XPT")
DSQTOT <- read.xport("nnhanes1516/DSQTOT_I.XPT")
DUQ <- read.xport("nnhanes1516/DUQ_I.XPT")
DXX <- read.xport("nnhanes1516/DXX_I.XPT")
ECQ <- read.xport("nnhanes1516/ECQ_I.XPT")
FLXCLN <- read.xport("nnhanes1516/FLXCLN_I.XPT")
FSQ <- read.xport("nnhanes1516/FSQ_I.XPT")
HEQ <- read.xport("nnhanes1516/HEQ_I.XPT")
HIQ <- read.xport("nnhanes1516/HIQ_I.XPT")
HOQ <- read.xport("nnhanes1516/HOQ_I.XPT")
HSQ <- read.xport("nnhanes1516/HSQ_I.XPT")
HUQ <- read.xport("nnhanes1516/HUQ_I.XPT")
IMQ <- read.xport("nnhanes1516/IMQ_I.XPT")
INQ <- read.xport("nnhanes1516/INQ_I.XPT")
KIQ <- read.xport("nnhanes1516/KIQ_U_I.XPT")
MCQ <- read.xport("nnhanes1516/MCQ_I.XPT")
OCQ <- read.xport("nnhanes1516/OCQ_I.XPT")
OHQ <- read.xport("nnhanes1516/OHQ_I.XPT")
OHXDEN <- read.xport("nnhanes1516/OHXDEN_I.XPT")
OHXREF <- read.xport("nnhanes1516/OHXREF_I.XPT")
PAQ <- read.xport("nnhanes1516/PAQ_I.XPT")
PFQ <- read.xport("nnhanes1516/PFQ_I.XPT")
PUQMEC <- read.xport("nnhanes1516/PUQMEC_I.XPT")
RHQ <- read.xport("nnhanes1516/RHQ_I.XPT")
RXQASA <- read.xport("nnhanes1516/RXQASA_I.XPT")
SLQ <- read.xport("nnhanes1516/SLQ_I.XPT")
SMQ <- read.xport("nnhanes1516/SMQ_I.XPT")
SMQFAM <- read.xport("nnhanes1516/SMQFAM_I.XPT")
SMQRTU <- read.xport("nnhanes1516/SMQRTU_I.XPT")
SMQSHS <- read.xport("nnhanes1516/SMQSHS_I.XPT")
SXQ <- read.xport("nnhanes1516/SXQ_I.XPT")
VTQ <- read.xport("nnhanes1516/VTQ_I.XPT")
WHQ <- read.xport("nnhanes1516/WHQ_I.XPT")
WHQMEC <- read.xport("nnhanes1516/WHQMEC_I.XPT")
AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)
DtoP <- merge(DtoP, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final1516 <- RtoW
write.table(final1516, file="finalTables/finalTable1516.txt")