library(SASxport)
ACQ<- read.xport("nnhanes1112/ACQ_G.XPT")
ALQ<- read.xport("nnhanes1112/ALQ_G.XPT")
AUQ<- read.xport("nnhanes1112/AUQ_G.XPT")
BMX<- read.xport("nnhanes1112/BMX_G.XPT")
BPQ<- read.xport("nnhanes1112/BPQ_G.XPT")
BPX<- read.xport("nnhanes1112/BPX_G.XPT")
CBQ<- read.xport("nnhanes1112/CBQ_G.XPT")
CDQ<- read.xport("nnhanes1112/CDQ_G.XPT")
CFQ<- read.xport("nnhanes1112/CFQ_G.XPT")
CKQ<- read.xport("nnhanes1112/CKQ_G.XPT")
CSQ<- read.xport("nnhanes1112/CSQ_G.XPT")
DBQ<- read.xport("nnhanes1112/DBQ_G.XPT")
DEMO<- read.xport("nnhanes1112/DEMO_G.XPT")
DEQ<- read.xport("nnhanes1112/DEQ_G.XPT")
DIQ<- read.xport("nnhanes1112/DIQ_G.XPT")
DPQ<- read.xport("nnhanes1112/DPQ_G.XPT")
DSQIDS <- read.xport("nnhanes1112/DSQIDS_G.XPT")
DSQTOT <- read.xport("nnhanes1112/DSQTOT_G.XPT")
DUQ <- read.xport("nnhanes1112/DUQ_G.XPT")
ECQ <- read.xport("nnhanes1112/ECQ_G.XPT")
FSQ <- read.xport("nnhanes1112/FSQ_G.XPT")
HCQ <- read.xport("nnhanes1112/HCQ_G.XPT")
HIQ <- read.xport("nnhanes1112/HIQ_G.XPT")
HOQ <- read.xport("nnhanes1112/HOQ_G.XPT")
HSQ <- read.xport("nnhanes1112/HSQ_G.XPT")
HUQ <- read.xport("nnhanes1112/HUQ_G.XPT")
IMQ <- read.xport("nnhanes1112/IMQ_G.XPT")
INQ <- read.xport("nnhanes1112/INQ_G.XPT")
KIQ <- read.xport("nnhanes1112/KIQ_U_G.XPT")
MCQ <- read.xport("nnhanes1112/MCQ_G.XPT")
OCQ <- read.xport("nnhanes1112/OCQ_G.XPT")
OHQ <- read.xport("nnhanes1112/OHQ_G.XPT")
PAQ <- read.xport("nnhanes1112/PAQ_G.XPT")
PFQ <- read.xport("nnhanes1112/PFQ_G.XPT")
PUQMEC <- read.xport("nnhanes1112/PUQMEC_G.XPT")
RDQ <- read.xport("nnhanes1112/RDQ_G.XPT")
RHQ <- read.xport("nnhanes1112/RHQ_G.XPT")
RXQASA <- read.xport("nnhanes1112/RXQASA_G.XPT")
SLQ <- read.xport("nnhanes1112/SLQ_G.XPT")
SMQ <- read.xport("nnhanes1112/SMQ_G.XPT")
SMQFAM <- read.xport("nnhanes1112/SMQFAM_G.XPT")
SMQRTU <- read.xport("nnhanes1112/SMQRTU_G.XPT")
SXQ <- read.xport("nnhanes1112/SXQ_G.XPT")
TBQ <- read.xport("nnhanes1112/TBQ_G.XPT")
VTQ <- read.xport("nnhanes1112/VTQ_G.XPT")
WHQ <- read.xport("nnhanes1112/WHQ_G.XPT")
WHQMEC <- read.xport("nnhanes1112/WHQMEC_G.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE) ###doesn't exist for 11/12
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)
DtoP <- merge(DtoP, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE) ###doesn't exist for 11/12
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)  ####doesn't exist for 11/12
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final1112 <- RtoW
write.table(final1112, file="finalTables/finalTable1112.txt")
