library(SASxport)
ACQ<- read.xport("ACQ_D.XPT")
AGQ<- read.xport("AGQ_D.XPT")
ALQ<- read.xport("ALQ_D.XPT")
AUQ<- read.xport("AUQ_D.XPT")
BHQ<- read.xport("BHQ_D.XPT")
BMX<- read.xport("BMX_D.XPT")
BPQ<- read.xport("BPQ_D.XPT")
BPX<- read.xport("BPX_D.XPT")
CDQ<- read.xport("CDQ_D.XPT")
DBQ<- read.xport("DBQ_D.XPT")
DEMO<- read.xport("DEMO_D.XPT")
DEQ<- read.xport("DEQ_D.XPT")
DIQ<- read.xport("DIQ_D.XPT")
DPQ<- read.xport("DPQ_D.XPT")
DSQ1 <- read.xport("DSQ1_D.XPT")
DSQ2 <- read.xport("DSQ2_D.XPT")
DUQ <- read.xport("DUQ_D.XPT")
ECQ <- read.xport("ECQ_D.XPT")
FSQ <- read.xport("FSQ_D.XPT")
HCQ <- read.xport("HCQ_D.XPT")
HIQ <- read.xport("HIQ_D.XPT")
HOQ <- read.xport("HOQ_D.XPT")
HSQ <- read.xport("HSQ_D.XPT")
HUQ <- read.xport("HUQ_D.XPT")
IMQ <- read.xport("IMQ_D.XPT")
KIQ <- read.xport("KIQ_U_D.XPT")
KIQP <- read.xport("KIQ_P_D.XPT")
MCQ <- read.xport("MCQ_D.XPT")
OCQ <- read.xport("OCQ_D.XPT")
OHQ <- read.xport("OHQ_D.XPT")
OSQ <- read.xport("OSQ_D.XPT")
PAQ <- read.xport("PAQ_D.XPT")
PAQIAF <- read.xport("PAQIAF_D.XPT")
PFQ <- read.xport("PFQ_D.XPT")
PSQ <- read.xport("PSQ_D.XPT")
PUQMEC <- read.xport("PUQMEC_D.XPT")
RDQ <- read.xport("RDQ_D.XPT")
RHQ <- read.xport("RHQ_D.XPT")
SLQ <- read.xport("SLQ_D.XPT")
SMQ <- read.xport("SMQ_D.XPT")
SMQFAM <- read.xport("SMQFAM_D.XPT")
SMQRTU <- read.xport("SMQRTU_D.XPT")
SSQ <- read.xport("SSQ_D.XPT")
SXQ <- read.xport("SXQ_D.XPT")
VIQ <- read.xport("VIQ_D.XPT")
WHQ <- read.xport("WHQ_D.XPT")
WHQMEC <- read.xport("WHQMEC_D.XPT")