library(SASxport)
ACQ<- read.xport("nnhanes0708/ACQ_E.XPT")
ALQ<- read.xport("nnhanes0708/ALQ_E.XPT")
AQQ<- read.xport("nnhanes0708/AQQ_E.XPT")
AUQ<- read.xport("nnhanes0708/AUQ_E.XPT")
BHQ<- read.xport("nnhanes0708/BHQ_E.XPT")
BMX<- read.xport("nnhanes0708/BMX_E.XPT")
BPQ<- read.xport("nnhanes0708/BPQ_E.XPT")
BPX<- read.xport("nnhanes0708/BPX_E.XPT")
CBQ<- read.xport("nnhanes0708/CBQ_E.XPT")
CDQ<- read.xport("nnhanes0708/CDQ_E.XPT")
DBQ<- read.xport("nnhanes0708/DBQ_E.XPT")
DEMO<- read.xport("nnhanes0708/DEMO_E.XPT")
DIQ<- read.xport("nnhanes0708/DIQ_E.XPT")
DPQ<- read.xport("nnhanes0708/DPQ_E.XPT")
DSQIDS <- read.xport("nnhanes0708/DSQIDS_E.XPT")
DSQTOT <- read.xport("nnhanes0708/DSQTOT_E.XPT")
DUQ <- read.xport("nnhanes0708/DUQ_E.XPT")
ECQ <- read.xport("nnhanes0708/ECQ_E.XPT")
FSQ <- read.xport("nnhanes0708/FSQ_E.XPT")
HCQ <- read.xport("nnhanes0708/HCQ_E.XPT")
HIQ <- read.xport("nnhanes0708/HIQ_E.XPT")
HOQ <- read.xport("nnhanes0708/HOQ_E.XPT")
HSQ <- read.xport("nnhanes0708/HSQ_E.XPT")
HUQ <- read.xport("nnhanes0708/HUQ_E.XPT")
IMQ <- read.xport("nnhanes0708/IMQ_E.XPT")
INQ <- read.xport("nnhanes0708/INQ_E.XPT")
KIQ <- read.xport("nnhanes0708/KIQ_U_E.XPT")
KIQP <- read.xport("nnhanes0708/KIQ_P_E.XPT")
MCQ <- read.xport("nnhanes0708/MCQ_E.XPT")
OCQ <- read.xport("nnhanes0708/OCQ_E.XPT")
OHQ <- read.xport("nnhanes0708/OHQ_E.XPT")
OSQ <- read.xport("nnhanes0708/OSQ_E.XPT")
PAQ <- read.xport("nnhanes0708/PAQ_E.XPT")
PFQ <- read.xport("nnhanes0708/PFQ_E.XPT")
PUQMEC <- read.xport("nnhanes0708/PUQMEC_E.XPT")
RDQ <- read.xport("nnhanes0708/RDQ_E.XPT")
RHQ <- read.xport("nnhanes0708/RHQ_E.XPT")
SLQ <- read.xport("nnhanes0708/SLQ_E.XPT")
SMQ <- read.xport("nnhanes0708/SMQ_E.XPT")
SMQFAM <- read.xport("nnhanes0708/SMQFAM_E.XPT")
SMQRTU <- read.xport("nnhanes0708/SMQRTU_E.XPT")
SSQ <- read.xport("nnhanes0708/SSQ_E.XPT")
SXQ <- read.xport("nnhanes0708/SXQ_E.XPT")
VIQ <- read.xport("nnhanes0708/VIQ_E.XPT")
WHQ <- read.xport("nnhanes0708/WHQ_E.XPT")
WHQMEC <- read.xport("nnhanes0708/WHQMEC_E.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE) ###doesn't exist for 07/08
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE) ###doesn't exist for 11/12
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)
DtoP <- merge(DtoP, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE) ###doesn't exist for 11/12
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE) ####doesn't exist for 09/10
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)  ####doesn't exist for 11/12
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final0708 <- RtoW
write.table(final0708, file="finalTables/finalTable0708.txt")
