library(SASxport)
ACQ<- read.xport("ACQ_F.XPT")
ALQ<- read.xport("ALQ_F.XPT")
ALQY<- read.xport("ALQY_F.XPT")
AQQ<- read.xport("AQQ_F.XPT")
ARQ<- read.xport("ARQ_F.XPT")
AUQ<- read.xport("AUQ_F.XPT")
BHQ<- read.xport("BHQ_F.XPT")
BMX<- read.xport("BMX_F.XPT")
BPQ<- read.xport("BPQ_F.XPT")
BPX<- read.xport("BPX_F.XPT")
CBQ<- read.xport("CBQ_F.XPT")
CBQPFA<- read.xport("CBQPFA_F.XPT")
CDQ<- read.xport("CDQ_F.XPT")
DBQ<- read.xport("DBQ_F.XPT")
DEMO<- read.xport("DEMO_F.XPT")
DEQ<- read.xport("DEQ_F.XPT")
DIQ<- read.xport("DIQ_F.XPT")
DPQ<- read.xport("DPQ_F.XPT")
DSQIDS <- read.xport("DSQIDS_F.XPT")
DSQTOT <- read.xport("DSQTOT_F.XPT")
DUQ <- read.xport("DUQ_F.XPT")
ECQ <- read.xport("ECQ_F.XPT")
FSQ <- read.xport("FSQ_F.XPT")
HCQ <- read.xport("HCQ_F.XPT")
HIQ <- read.xport("HIQ_F.XPT")
HOQ <- read.xport("HOQ_F.XPT")
HSQ <- read.xport("HSQ_F.XPT")
HUQ <- read.xport("HUQ_F.XPT")
IMQ <- read.xport("IMQ_F.XPT")
INQ <- read.xport("INQ_F.XPT")
KIQ <- read.xport("KIQ_U_F.XPT")
MCQ <- read.xport("MCQ_F.XPT")
OCQ <- read.xport("OCQ_F.XPT")
OHQ <- read.xport("OHQ_F.XPT")
OSQ <- read.xport("OSQ_F.XPT")
PAQ <- read.xport("PAQ_F.XPT")
PFQ <- read.xport("PFQ_F.XPT")
PUQMEC <- read.xport("PUQMEC_F.XPT")
RDQ <- read.xport("RDQ_F.XPT")
RHQ <- read.xport("RHQ_F.XPT")
SLQ <- read.xport("SLQ_F.XPT")
SMQ <- read.xport("SMQ_F.XPT")
SMQFAM <- read.xport("SMQFAM_F.XPT")
SMQRTU <- read.xport("SMQRTU_F.XPT")
SXQ <- read.xport("SXQ_F.XPT")
VTQ <- read.xport("VTQ_F.XPT")
WHQ <- read.xport("WHQ_F.XPT")
WHQMEC <- read.xport("WHQMEC_F.XPT")