library(SASxport)
ACQ<- read.xport("nnhanes0304/ACQ_C.XPT")
ALQ<- read.xport("nnhanes0304/ALQ_C.XPT")
AUQ<- read.xport("nnhanes0304/AUQ_C.XPT")
BAQ<- read.xport("nnhanes0304/BAQ_C.XPT")
BMX<- read.xport("nnhanes0304/BMX_C.XPT")
BPQ<- read.xport("nnhanes0304/BPQ_C.XPT")
BPX<- read.xport("nnhanes0304/BPX_C.XPT")
CIQDEP<- read.xport("nnhanes0304/CIQDEP_C.XPT")
CIQPAN<- read.xport("nnhanes0304/CIQPAN_C.XPT")
CDQ<- read.xport("nnhanes0304/CDQ_C.XPT")
DBQ<- read.xport("nnhanes0304/DBQ_C.XPT")
DEMO<- read.xport("nnhanes0304/DEMO_C.XPT")
DEQ<- read.xport("nnhanes0304/DEQ_C.XPT")
DIQ<- read.xport("nnhanes0304/DIQ_C.XPT")
DSQ1 <- read.xport("nnhanes0304/DSQ1_C.XPT")
DSQ2 <- read.xport("nnhanes0304/DSQ2_C.XPT")
DUQ <- read.xport("nnhanes0304/DUQ_C.XPT")
ECQ <- read.xport("nnhanes0304/ECQ_C.XPT")
FSQ <- read.xport("nnhanes0304/FSQ_C.XPT")
HCQ <- read.xport("nnhanes0304/HCQ_C.XPT")
HIQ <- read.xport("nnhanes0304/HIQ_C.XPT")
HOQ <- read.xport("nnhanes0304/HOQ_C.XPT")
HSQ <- read.xport("nnhanes0304/HSQ_C.XPT")
HUQ <- read.xport("nnhanes0304/HUQ_C.XPT")
IMQ <- read.xport("nnhanes0304/IMQ_C.XPT")
KIQ <- read.xport("nnhanes0304/KIQ_U_C.XPT")
KIQP <- read.xport("nnhanes0304/KIQ_P_C.XPT")
MCQ <- read.xport("nnhanes0304/MCQ_C.XPT")
MPQ <- read.xport("nnhanes0304/MPQ_C.XPT")
OCQ <- read.xport("nnhanes0304/OCQ_C.XPT")
OHQ <- read.xport("nnhanes0304/OHQ_C.XPT")
OSQ <- read.xport("nnhanes0304/OSQ_C.XPT")
PAQ <- read.xport("nnhanes0304/PAQ_C.XPT")
PAQIAF <- read.xport("nnhanes0304/PAQIAF_C.XPT")
PFQ <- read.xport("nnhanes0304/PFQ_C.XPT")
PSQ <- read.xport("nnhanes0304/PSQ_C.XPT")
PUQ <- read.xport("nnhanes0304/PUQ_C.XPT")
RDQ <- read.xport("nnhanes0304/RDQ_C.XPT")
RHQ <- read.xport("nnhanes0304/RHQ_C.XPT")
RXQANA <- read.xport("nnhanes0304/RXQANA_C.XPT")
SMQ <- read.xport("nnhanes0304/SMQ_C.XPT")
SMQFAM <- read.xport("nnhanes0304/SMQFAM_C.XPT")
SMQMEC <- read.xport("nnhanes0304/SMQMEC_C.XPT")
SSQ <- read.xport("nnhanes0304/SSQ_C.XPT")
SXQ <- read.xport("nnhanes0304/SXQ_C.XPT")
VIQ <- read.xport("nnhanes0304/VIQ_C.XPT")
WHQ <- read.xport("nnhanes0304/WHQ_C.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE) ###doesn't exist for 07/08
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE) ###doesn't exist for 11/12
#AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE) ###doesn't exist for 03/04
#DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)  ###doesn't exist for 05/06
DtoP <- merge(DUQ, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE) ###doesn't exist for 11/12
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE) ####doesn't exist for 03/04
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE) ####doesn't exist for 09/10
#RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)  ####doesn't exist for 03/04
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE) ####doesn't exist for 03/04
#RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)  ####doesn't exist for 11/12
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)  ####doesn't exist for 03/04
final0304 <- RtoW
write.table(final0304, file="finalTables/finalTable0304.txt")
