library(SASxport)
ACQ<- read.xport("nnhanes1718/ACQ_J.XPT")
AUQ<- read.xport("nnhanes1718/AUQ_J.XPT")
BMX<- read.xport("nnhanes1718/BMX_J.XPT")
BPQ<- read.xport("nnhanes1718/BPQ_J.XPT")
BPX<- read.xport("nnhanes1718/BPX_J.XPT")
CDQ<- read.xport("nnhanes1718/CDQ_J.XPT")
DBQ<- read.xport("nnhanes1718/DBQ_J.XPT")
DEMO<- read.xport("nnhanes1718/DEMO_J.XPT")
DEQ<- read.xport("nnhanes1718/DEQ_J.XPT")
DIQ<- read.xport("nnhanes1718/DIQ_J.XPT")
DLQ<- read.xport("nnhanes1718/DLQ_J.XPT")
DPQ<- read.xport("nnhanes1718/DPQ_J.XPT")
#DSQIDS <- read.xport("nnhanes1718/DSQIDS_J.XPT")
DSQTOT <- read.xport("nnhanes1718/DSQTOT_J.XPT")
DUQ <- read.xport("nnhanes1718/DUQ_J.XPT")
ECQ <- read.xport("nnhanes1718/ECQ_J.XPT")
HEQ <- read.xport("nnhanes1718/HEQ_J.XPT")
HIQ <- read.xport("nnhanes1718/HIQ_J.XPT")
HSQ <- read.xport("nnhanes1718/HSQ_J.XPT")
HUQ <- read.xport("nnhanes1718/HUQ_J.XPT")
IMQ <- read.xport("nnhanes1718/IMQ_J.XPT")
KIQ <- read.xport("nnhanes1718/KIQ_U_J.XPT")
MCQ <- read.xport("nnhanes1718/MCQ_J.XPT")
OCQ <- read.xport("nnhanes1718/OCQ_J.XPT")
OHQ <- read.xport("nnhanes1718/OHQ_J.XPT")
OSQ <- read.xport("nnhanes1718/OSQ_J.XPT")  ### Not in 15/16
PAQ <- read.xport("nnhanes1718/PAQ_J.XPT")
PAQY <- read.xport("nnhanes1718/PAQY_J.XPT")  ### Not in 15/16
PFQ <- read.xport("nnhanes1718/PFQ_J.XPT")
PUQMEC <- read.xport("nnhanes1718/PUQMEC_J.XPT")
RHQ <- read.xport("nnhanes1718/RHQ_J.XPT")
RXQASA <- read.xport("nnhanes1718/RXQASA_J.XPT")
SLQ <- read.xport("nnhanes1718/SLQ_J.XPT")
SMQ <- read.xport("nnhanes1718/SMQ_J.XPT")
SMQFAM <- read.xport("nnhanes1718/SMQFAM_J.XPT")
SMQRTU <- read.xport("nnhanes1718/SMQRTU_J.XPT")
SMQSHS <- read.xport("nnhanes1718/SMQSHS_J.XPT")
WHQ <- read.xport("nnhanes1718/WHQ_J.XPT")
WHQMEC <- read.xport("nnhanes1718/WHQMEC_J.XPT")
AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
#DtoP <- merge(DSQIDS, DSQTOT, BY ="SEQN", all = TRUE)
DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)
DtoP <- merge(DtoP, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final1718 <- RtoW
write.table(final1718, file="finalTables/finalTable1718.txt")
