library(SASxport)
ACQ<- read.xport("ACQ_C.XPT")
ALQ<- read.xport("ALQ_C.XPT")
AUQ<- read.xport("AUQ_C.XPT")
BAQ<- read.xport("BAQ_C.XPT")
BMX<- read.xport("BMX_C.XPT")
BPQ<- read.xport("BPQ_C.XPT")
BPX<- read.xport("BPX_C.XPT")
CIQDEP<- read.xport("CIQDEP_C.XPT")
CIQPAN<- read.xport("CIQPAN_C.XPT")
CDQ<- read.xport("CDQ_C.XPT")
DBQ<- read.xport("DBQ_C.XPT")
DEMO<- read.xport("DEMO_C.XPT")
DEQ<- read.xport("DEQ_C.XPT")
DIQ<- read.xport("DIQ_C.XPT")
DSQ1 <- read.xport("DSQ1_C.XPT")
DSQ2 <- read.xport("DSQ2_C.XPT")
DUQ <- read.xport("DUQ_C.XPT")
ECQ <- read.xport("ECQ_C.XPT")
FSQ <- read.xport("FSQ_C.XPT")
HCQ <- read.xport("HCQ_C.XPT")
HIQ <- read.xport("HIQ_C.XPT")
HOQ <- read.xport("HOQ_C.XPT")
HSQ <- read.xport("HSQ_C.XPT")
HUQ <- read.xport("HUQ_C.XPT")
IMQ <- read.xport("IMQ_C.XPT")
KIQ <- read.xport("KIQ_U_C.XPT")
KIQP <- read.xport("KIQ_P_C.XPT")
MCQ <- read.xport("MCQ_C.XPT")
MPQ <- read.xport("MPQ_C.XPT")
OCQ <- read.xport("OCQ_C.XPT")
OHQ <- read.xport("OHQ_C.XPT")
OSQ <- read.xport("OSQ_C.XPT")
PAQ <- read.xport("PAQ_C.XPT")
PAQIAF <- read.xport("PAQIAF_C.XPT")
PFQ <- read.xport("PFQ_C.XPT")
PSQ <- read.xport("PSQ_C.XPT")
PUQ <- read.xport("PUQ_C.XPT")
RDQ <- read.xport("RDQ_C.XPT")
RHQ <- read.xport("RHQ_C.XPT")
RXQANA <- read.xport("RXQANA_C.XPT")
SMQ <- read.xport("SMQ_C.XPT")
SMQFAM <- read.xport("SMQFAM_C.XPT")
SMQMEC <- read.xport("SMQMEC_C.XPT")
SSQ <- read.xport("SSQ_C.XPT")
SXQ <- read.xport("SXQ_C.XPT")
VIQ <- read.xport("VIQ_C.XPT")
WHQ <- read.xport("WHQ_C.XPT")
