library(SASxport)
ACQ<- read.xport("ACQ_E.XPT")
ALQ<- read.xport("ALQ_E.XPT")
AQQ<- read.xport("AQQ_E.XPT")
AUQ<- read.xport("AUQ_E.XPT")
BHQ<- read.xport("BHQ_E.XPT")
BMX<- read.xport("BMX_E.XPT")
BPQ<- read.xport("BPQ_E.XPT")
BPX<- read.xport("BPX_E.XPT")
CBQ<- read.xport("CBQ_E.XPT")
CDQ<- read.xport("CDQ_E.XPT")
DBQ<- read.xport("DBQ_E.XPT")
DEMO<- read.xport("DEMO_E.XPT")
DIQ<- read.xport("DIQ_E.XPT")
DPQ<- read.xport("DPQ_E.XPT")
DSQIDS <- read.xport("DSQIDS_E.XPT")
DSQTOT <- read.xport("DSQTOT_E.XPT")
DUQ <- read.xport("DUQ_E.XPT")
ECQ <- read.xport("ECQ_E.XPT")
FSQ <- read.xport("FSQ_E.XPT")
HCQ <- read.xport("HCQ_E.XPT")
HIQ <- read.xport("HIQ_E.XPT")
HOQ <- read.xport("HOQ_E.XPT")
HSQ <- read.xport("HSQ_E.XPT")
HUQ <- read.xport("HUQ_E.XPT")
IMQ <- read.xport("IMQ_E.XPT")
INQ <- read.xport("INQ_E.XPT")
KIQ <- read.xport("KIQ_U_E.XPT")
KIQP <- read.xport("KIQ_P_E.XPT")
MCQ <- read.xport("MCQ_E.XPT")
OCQ <- read.xport("OCQ_E.XPT")
OHQ <- read.xport("OHQ_E.XPT")
OSQ <- read.xport("OSQ_E.XPT")
PAQ <- read.xport("PAQ_E.XPT")
PFQ <- read.xport("PFQ_E.XPT")
PUQMEC <- read.xport("PUQMEC_E.XPT")
RDQ <- read.xport("RDQ_E.XPT")
RHQ <- read.xport("RHQ_E.XPT")
SLQ <- read.xport("SLQ_E.XPT")
SMQ <- read.xport("SMQ_E.XPT")
SMQFAM <- read.xport("SMQFAM_E.XPT")
SMQRTU <- read.xport("SMQRTU_E.XPT")
SSQ <- read.xport("SSQ_E.XPT")
SXQ <- read.xport("SXQ_E.XPT")
VTQ <- read.xport("VTQ_E.XPT")
WHQ <- read.xport("WHQ_E.XPT")
WHQMEC <- read.xport("WHQMEC_E.XPT")