library(SASxport)
ACQ<- read.xport("ACQ_B.XPT")
ALQ<- read.xport("ALQ_B.XPT")
AUQ<- read.xport("AUQ_B.XPT")
BAQ<- read.xport("BAQ_B.XPT")
BMX<- read.xport("BMX_B.XPT")
BPQ<- read.xport("BPQ_B.XPT")
BPX<- read.xport("BPX_B.XPT")
CIQDEP<- read.xport("CIQDEP_B.XPT")
CIQGAD<- read.xport("CIQGAD_B.XPT")
CDQ<- read.xport("CDQ_B.XPT")
CFQ<- read.xport("CFQ_B.XPT")
DBQ<- read.xport("DBQ_B.XPT")
DEMO<- read.xport("DEMO_B.XPT")
DEQ<- read.xport("DEQ_B.XPT")
DIQ<- read.xport("DIQ_B.XPT")
DSQ1 <- read.xport("DSQ1_B.XPT")
DSQ2 <- read.xport("DSQ2_B.XPT")
DUQ <- read.xport("DUQ_B.XPT")
ECQ <- read.xport("ECQ_B.XPT")
FSQ <- read.xport("FSQ_B.XPT")
HCQ <- read.xport("HCQ_B.XPT")
HIQ <- read.xport("HIQ_B.XPT")
HOQ <- read.xport("HOQ_B.XPT")
HSQ <- read.xport("HSQ_B.XPT")
HUQ <- read.xport("HUQ_B.XPT")
IMQ <- read.xport("IMQ_B.XPT")
KIQ <- read.xport("KIQ_U_B.XPT")
KIQP <- read.xport("KIQ_P_B.XPT")
MCQ <- read.xport("MCQ_B.XPT")
MPQ <- read.xport("MPQ_B.XPT")
OCQ <- read.xport("OCQ_B.XPT")
OHQ <- read.xport("OHQ_B.XPT")
OSQ <- read.xport("OSQ_B.XPT")
PAQ <- read.xport("PAQ_B.XPT")
PAQIAF <- read.xport("PAQIAF_B.XPT")
PFQ <- read.xport("PFQ_B.XPT")
PUQ <- read.xport("PUQ_B.XPT")
RDQ <- read.xport("RDQ_B.XPT")
RHQ <- read.xport("RHQ_B.XPT")
RXQANA <- read.xport("RXQANA_B.XPT")
SMQ <- read.xport("SMQ_B.XPT")
SMQFAM <- read.xport("SMQFAM_B.XPT")
SSQ <- read.xport("SSQ_B.XPT")
SXQ <- read.xport("SXQ_B.XPT")
VIQ <- read.xport("VIQ_B.XPT")
WHQ <- read.xport("WHQ_B.XPT")