library(SASxport)
ACQ<- read.xport("ACQ_I.XPT")
ALQ<- read.xport("ALQ_I.XPT")
AUQ<- read.xport("AUQ_I.XPT")
AUX<- read.xport("AUX_I.XPT")
AUXAR<- read.xport("AUXAR_I.XPT")
BMX<- read.xport("BMX_I.XPT")
BPQ<- read.xport("BPQ_I.XPT")
BPX<- read.xport("BPX_I.XPT")
CBQ<- read.xport("CBQ_I.XPT")
CDQ<- read.xport("CDQ_I.XPT")
DBQ<- read.xport("DBQ_I.XPT")
DEMO<- read.xport("DEMO_I.XPT")
DEQ<- read.xport("DEQ_I.XPT")
DIQ<- read.xport("DIQ_I.XPT")
DLQ<- read.xport("DLQ_I.XPT")
DPQ<- read.xport("DPQ_I.XPT")
DSQIDS <- read.xport("DSQIDS_I.XPT")
DSQTOT <- read.xport("DSQTOT_I.XPT")
DUQ <- read.xport("DUQ_I.XPT")
DXX <- read.xport("DXX_I.XPT")
ECQ <- read.xport("ECQ_I.XPT")
FLXCLN <- read.xport("FLXCLN_I.XPT")
FSQ <- read.xport("FSQ_I.XPT")
HEQ <- read.xport("HEQ_I.XPT")
HIQ <- read.xport("HIQ_I.XPT")
HOQ <- read.xport("HOQ_I.XPT")
HSQ <- read.xport("HSQ_I.XPT")
HUQ <- read.xport("HUQ_I.XPT")
IMQ <- read.xport("IMQ_I.XPT")
INQ <- read.xport("INQ_I.XPT")
KIQ <- read.xport("KIQ_U_I.XPT")
MCQ <- read.xport("MCQ_I.XPT")
OCQ <- read.xport("OCQ_I.XPT")
OHQ <- read.xport("OHQ_I.XPT")
OHXDEN <- read.xport("OHXDEN_I.XPT")
OHXREF <- read.xport("OHXREF_I.XPT")
PAQ <- read.xport("PAQ_I.XPT")
PFQ <- read.xport("PFQ_I.XPT")
PUQMEC <- read.xport("PUQMEC_I.XPT")
RHQ <- read.xport("RHQ_I.XPT")
RXQASA <- read.xport("RXQASA_I.XPT")
SLQ <- read.xport("SLQ_I.XPT")
SMQ <- read.xport("SMQ_I.XPT")
SMQFAM <- read.xport("SMQFAM_I.XPT")
SMQRTU <- read.xport("SMQRTU_I.XPT")
SMQSHS <- read.xport("SMQSHS_I.XPT")
SXQ <- read.xport("SXQ_I.XPT")
VTQ <- read.xport("VTQ_I.XPT")
WHQ <- read.xport("WHQ_I.XPT")
WHQMEC <- read.xport("WHQMEC_I.XPT")
