library(SASxport)
ACQ<- read.xport("nnhanes0910/ACQ_F.XPT")
ALQ<- read.xport("nnhanes0910/ALQ_F.XPT")
ALQY<- read.xport("nnhanes0910/ALQY_F.XPT")
AQQ<- read.xport("nnhanes0910/AQQ_F.XPT")
ARQ<- read.xport("nnhanes0910/ARQ_F.XPT")
AUQ<- read.xport("nnhanes0910/AUQ_F.XPT")
BHQ<- read.xport("nnhanes0910/BHQ_F.XPT")
BMX<- read.xport("nnhanes0910/BMX_F.XPT")
BPQ<- read.xport("nnhanes0910/BPQ_F.XPT")
BPX<- read.xport("nnhanes0910/BPX_F.XPT")
CBQ<- read.xport("nnhanes0910/CBQ_F.XPT")
CBQPFA<- read.xport("nnhanes0910/CBQPFA_F.XPT")
CDQ<- read.xport("nnhanes0910/CDQ_F.XPT")
DBQ<- read.xport("nnhanes0910/DBQ_F.XPT")
DEMO<- read.xport("nnhanes0910/DEMO_F.XPT")
DEQ<- read.xport("nnhanes0910/DEQ_F.XPT")
DIQ<- read.xport("nnhanes0910/DIQ_F.XPT")
DPQ<- read.xport("nnhanes0910/DPQ_F.XPT")
DSQIDS <- read.xport("nnhanes0910/DSQIDS_F.XPT")
DSQTOT <- read.xport("nnhanes0910/DSQTOT_F.XPT")
DUQ <- read.xport("nnhanes0910/DUQ_F.XPT")
ECQ <- read.xport("nnhanes0910/ECQ_F.XPT")
FSQ <- read.xport("nnhanes0910/FSQ_F.XPT")
HCQ <- read.xport("nnhanes0910/HCQ_F.XPT")
HIQ <- read.xport("nnhanes0910/HIQ_F.XPT")
HOQ <- read.xport("nnhanes0910/HOQ_F.XPT")
HSQ <- read.xport("nnhanes0910/HSQ_F.XPT")
HUQ <- read.xport("nnhanes0910/HUQ_F.XPT")
IMQ <- read.xport("nnhanes0910/IMQ_F.XPT")
INQ <- read.xport("nnhanes0910/INQ_F.XPT")
KIQ <- read.xport("nnhanes0910/KIQ_U_F.XPT")
MCQ <- read.xport("nnhanes0910/MCQ_F.XPT")
OCQ <- read.xport("nnhanes0910/OCQ_F.XPT")
OHQ <- read.xport("nnhanes0910/OHQ_F.XPT")
OSQ <- read.xport("nnhanes0910/OSQ_F.XPT")
PAQ <- read.xport("nnhanes0910/PAQ_F.XPT")
PFQ <- read.xport("nnhanes0910/PFQ_F.XPT")
PUQMEC <- read.xport("nnhanes0910/PUQMEC_F.XPT")
RDQ <- read.xport("nnhanes0910/RDQ_F.XPT")
RHQ <- read.xport("nnhanes0910/RHQ_F.XPT")
SLQ <- read.xport("nnhanes0910/SLQ_F.XPT")
SMQ <- read.xport("nnhanes0910/SMQ_F.XPT")
SMQFAM <- read.xport("nnhanes0910/SMQFAM_F.XPT")
SMQRTU <- read.xport("nnhanes0910/SMQRTU_F.XPT")
SXQ <- read.xport("nnhanes0910/SXQ_F.XPT")
VTQ <- read.xport("nnhanes0910/VTQ_F.XPT")
WHQ <- read.xport("nnhanes0910/WHQ_F.XPT")
WHQMEC <- read.xport("nnhanes0910/WHQMEC_F.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE) ###doesn't exist for 11/12
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)
DtoP <- merge(DtoP, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE) ###doesn't exist for 11/12
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE) ####doesn't exist for 09/10
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)  ####doesn't exist for 11/12
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final0910 <- RtoW
write.table(final0910, file="finalTables/finalTable0910.txt")
