library(SASxport)
ACQ<- read.xport("ACQ_H.XPT")
ALQ<- read.xport("ALQ_H.XPT")
BPQ<- read.xport("BPQ_H.XPT")
CBQ<- read.xport("CBQ_H.XPT")
CDQ<- read.xport("CDQ_H.XPT")
CFQ<- read.xport("CFQ_H.XPT")
CKQ<- read.xport("CKQ_H.XPT")
CSQ<- read.xport("CSQ_H.XPT")
DBQ<- read.xport("DBQ_H.XPT")
DEMO<- read.xport("DEMO_H.XPT")
DEQ<- read.xport("DEQ_H.XPT")
DIQ<- read.xport("DIQ_H.XPT")
DLQ<- read.xport("DLQ_H.XPT")
DPQ<- read.xport("DPQ_H.XPT")
DSQIDS <- read.xport("DSQIDS_H.XPT")
DSQTOT <- read.xport("DSQTOT_H.XPT")
DUQ <- read.xport("DUQ_H.XPT")
ECQ <- read.xport("ECQ_H.XPT")
FSQ <- read.xport("FSQ_H.XPT")
HEQ <- read.xport("HEQ_H.XPT")
HIQ <- read.xport("HIQ_H.XPT")
HOQ <- read.xport("HOQ_H.XPT")
HSQ <- read.xport("HSQ_H.XPT")
HUQ <- read.xport("HUQ_H.XPT")
IMQ <- read.xport("IMQ_H.XPT")
INQ <- read.xport("INQ_H.XPT")
KIQ <- read.xport("KIQ_U_H.XPT")
MCQ <- read.xport("MCQ_H.XPT")
OCQ <- read.xport("OCQ_H.XPT")
OHQ <- read.xport("OHQ_H.XPT")
OSQ <- read.xport("OSQ_H.XPT")
PAQ <- read.xport("PAQ_H.XPT")
PFQ <- read.xport("PFQ_H.XPT")
PUQMEC <- read.xport("PUQMEC_H.XPT")
RHQ <- read.xport("RHQ_H.XPT")
RXQASA <- read.xport("RXQASA_H.XPT")
SLQ <- read.xport("SLQ_H.XPT")
SMQ <- read.xport("SMQ_H.XPT")
SMQFAM <- read.xport("SMQFAM_H.XPT")
SMQRTU <- read.xport("SMQRTU_H.XPT")
SMQSHS <- read.xport("SMQSHS_H.XPT")
SXQ <- read.xport("SXQ_H.XPT")
VTQ <- read.xport("VTQ_H.XPT")
WHQ <- read.xport("WHQ_H.XPT")
WHQMEC <- read.xport("WHQMEC_H.XPT")