library(SASxport)
ACQ<- read.xport("ACQ.XPT")
ALQ<- read.xport("ALQ.XPT")
AUQ<- read.xport("AUQ.XPT")
BAQ<- read.xport("BAQ.XPT")
BMX<- read.xport("BMX.XPT")
BPQ<- read.xport("BPQ.XPT")
BPX<- read.xport("BPX.XPT")
CIQGAD<- read.xport("CIQGAD.XPT")
# check CIQMDEP AND CIQPANIC
CIQDEP<- read.xport("CIQMDEP.XPT")
CIQPAN<- read.xport("CIQPANIC.XPT")
CDQ<- read.xport("CDQ.XPT")
CFQ<- read.xport("CFQ.XPT")
DBQ<- read.xport("DBQ.XPT")
DEMO<- read.xport("DEMO.XPT")
DEQ<- read.xport("DEQ.XPT")
DIQ<- read.xport("DIQ.XPT")
DSQ1 <- read.xport("DSQFILE1.XPT")
DSQ2 <- read.xport("DSQFILE2.XPT")
DUQ <- read.xport("DUQ.XPT")
ECQ <- read.xport("ECQ.XPT")
FSQ <- read.xport("FSQ.XPT")
HIQ <- read.xport("HIQ.XPT")
HOQ <- read.xport("HOQ.XPT")
HSQ <- read.xport("HSQ.XPT")
HUQ <- read.xport("HUQ.XPT")
IMQ <- read.xport("IMQ.XPT")
#check KIQ variable
KIQ <- read.xport("KIQ.XPT")
MCQ <- read.xport("MCQ.XPT")
MPQ <- read.xport("MPQ.XPT")
OCQ <- read.xport("OCQ.XPT")
OHQ <- read.xport("OHQ.XPT")
OSQ <- read.xport("OSQ.XPT")
PAQ <- read.xport("PAQ.XPT")
PAQIAF <- read.xport("PAQIAF.XPT")
PFQ <- read.xport("PFQ.XPT")
PUQ <- read.xport("PUQ.XPT")
PUQ <- read.xport("PUQ.XPT")
RDQ <- read.xport("RDQ.XPT")
RHQ <- read.xport("RHQ.XPT")
RXQANA <- read.xport("RXQ_ANA.XPT")
SMQ <- read.xport("SMQ.XPT")
SMQFAM <- read.xport("SMQFAM.XPT")
SMQMEC <- read.xport("SMQMEC.XPT")
SSQ <- read.xport("SSQ.XPT")
SXQ <- read.xport("SXQ.XPT")
SXQ <- read.xport("SXQ.XPT")
TBQ <- read.xport("TBQ.XPT")
VIQ <- read.xport("VIQ.XPT")
WHQ <- read.xport("WHQ.XPT")