library(SASxport)
ACQ<- read.xport("nnhanes0506/ACQ_D.XPT")
AGQ<- read.xport("nnhanes0506/AGQ_D.XPT")
ALQ<- read.xport("nnhanes0506/ALQ_D.XPT")
AUQ<- read.xport("nnhanes0506/AUQ_D.XPT")
BHQ<- read.xport("nnhanes0506/BHQ_D.XPT")
BMX<- read.xport("nnhanes0506/BMX_D.XPT")
BPQ<- read.xport("nnhanes0506/BPQ_D.XPT")
BPX<- read.xport("nnhanes0506/BPX_D.XPT")
CDQ<- read.xport("nnhanes0506/CDQ_D.XPT")
DBQ<- read.xport("nnhanes0506/DBQ_D.XPT")
DEMO<- read.xport("nnhanes0506/DEMO_D.XPT")
DEQ<- read.xport("nnhanes0506/DEQ_D.XPT")
DIQ<- read.xport("nnhanes0506/DIQ_D.XPT")
DPQ<- read.xport("nnhanes0506/DPQ_D.XPT")
DSQ1 <- read.xport("nnhanes0506/DSQ1_D.XPT")
DSQ2 <- read.xport("nnhanes0506/DSQ2_D.XPT")
DUQ <- read.xport("nnhanes0506/DUQ_D.XPT")
ECQ <- read.xport("nnhanes0506/ECQ_D.XPT")
FSQ <- read.xport("nnhanes0506/FSQ_D.XPT")
HCQ <- read.xport("nnhanes0506/HCQ_D.XPT")
HIQ <- read.xport("nnhanes0506/HIQ_D.XPT")
HOQ <- read.xport("nnhanes0506/HOQ_D.XPT")
HSQ <- read.xport("nnhanes0506/HSQ_D.XPT")
HUQ <- read.xport("nnhanes0506/HUQ_D.XPT")
IMQ <- read.xport("nnhanes0506/IMQ_D.XPT")
KIQ <- read.xport("nnhanes0506/KIQ_U_D.XPT")
KIQP <- read.xport("nnhanes0506/KIQ_P_D.XPT")
MCQ <- read.xport("nnhanes0506/MCQ_D.XPT")
OCQ <- read.xport("nnhanes0506/OCQ_D.XPT")
OHQ <- read.xport("nnhanes0506/OHQ_D.XPT")
OSQ <- read.xport("nnhanes0506/OSQ_D.XPT")
PAQ <- read.xport("nnhanes0506/PAQ_D.XPT")
PAQIAF <- read.xport("nnhanes0506/PAQIAF_D.XPT")
PFQ <- read.xport("nnhanes0506/PFQ_D.XPT")
PSQ <- read.xport("nnhanes0506/PSQ_D.XPT")
PUQMEC <- read.xport("nnhanes0506/PUQMEC_D.XPT")
RDQ <- read.xport("nnhanes0506/RDQ_D.XPT")
RHQ <- read.xport("nnhanes0506/RHQ_D.XPT")
SLQ <- read.xport("nnhanes0506/SLQ_D.XPT")
SMQ <- read.xport("nnhanes0506/SMQ_D.XPT")
SMQFAM <- read.xport("nnhanes0506/SMQFAM_D.XPT")
SMQRTU <- read.xport("nnhanes0506/SMQRTU_D.XPT")
SSQ <- read.xport("nnhanes0506/SSQ_D.XPT")
SXQ <- read.xport("nnhanes0506/SXQ_D.XPT")
VIQ <- read.xport("nnhanes0506/VIQ_D.XPT")
WHQ <- read.xport("nnhanes0506/WHQ_D.XPT")
WHQMEC <- read.xport("nnhanes0506/WHQMEC_D.XPT")

AtoD <- merge( DEMO, ACQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, AUQ, by ="SEQN", all = TRUE) ###doesn't exist for 13/14
AtoD <- merge( AtoD, BMX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, BPQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, BPX, by ="SEQN", all = TRUE) 
AtoD <- merge( AtoD, CDQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DBQ, by ="SEQN", all = TRUE)
AtoD <- merge( AtoD, DEMO, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DEQ, by ="SEQN", all = TRUE) ###doesn't exist for 07/08
AtoD <- merge( AtoD, DIQ, by ="SEQN", all = TRUE)
#AtoD <- merge( AtoD, DLQ, by ="SEQN", all = TRUE) ###doesn't exist for 11/12
AtoD <- merge( AtoD, DPQ, by ="SEQN", all = TRUE)
#DtoP <- merge(AtoD, DSQTOT, by="SEQN", all=TRUE)  ###doesn't exist for 05/06
DtoP <- merge(DUQ, AtoD, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, HEQ, BY ="SEQN", all = TRUE) ###doesn't exist for 11/12
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, OSQ, BY ="SEQN", all = TRUE)  #######doesn't exist for 15/16
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all = TRUE)
#DtoP <- merge(DtoP, PAQY, BY ="SEQN", all = TRUE)  #####doesn't exist for 15/16
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all = TRUE)
RtoW <- merge(DtoP, RHQ, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, RXQASA, by = "SEQN",all = TRUE) ####doesn't exist for 09/10
RtoW <- merge(RtoW, SLQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all = TRUE)
#RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all = TRUE)  ####doesn't exist for 11/12
RtoW <- merge(RtoW, WHQ, by = "SEQN",all = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all = TRUE)
final0506 <- RtoW
write.table(final0506, file="finalTables/finalTable0506.txt")
