library(SASxport)
ACQ<- read.xport("ACQ_G.XPT")
ALQ<- read.xport("ALQ_G.XPT")
AUQ<- read.xport("AUQ_G.XPT")
BMX<- read.xport("BMX_G.XPT")
BPQ<- read.xport("BPQ_G.XPT")
BPX<- read.xport("BPX_G.XPT")
CBQ<- read.xport("CBQ_G.XPT")
CDQ<- read.xport("CDQ_G.XPT")
CFQ<- read.xport("CFQ_G.XPT")
CKQ<- read.xport("CKQ_G.XPT")
CSQ<- read.xport("CSQ_G.XPT")
DBQ<- read.xport("DBQ_G.XPT")
DEMO<- read.xport("DEMO_G.XPT")
DEQ<- read.xport("DEQ_G.XPT")
DIQ<- read.xport("DIQ_G.XPT")
DPQ<- read.xport("DPQ_G.XPT")
DSQIDS <- read.xport("DSQIDS_G.XPT")
DSQTOT <- read.xport("DSQTOT_G.XPT")
DUQ <- read.xport("DUQ_G.XPT")
ECQ <- read.xport("ECQ_G.XPT")
FSQ <- read.xport("FSQ_G.XPT")
HCQ <- read.xport("HCQ_G.XPT")
HIQ <- read.xport("HIQ_G.XPT")
HOQ <- read.xport("HOQ_G.XPT")
HSQ <- read.xport("HSQ_G.XPT")
HUQ <- read.xport("HUQ_G.XPT")
IMQ <- read.xport("IMQ_G.XPT")
INQ <- read.xport("INQ_G.XPT")
KIQ <- read.xport("KIQ_U_G.XPT")
MCQ <- read.xport("MCQ_G.XPT")
OCQ <- read.xport("OCQ_G.XPT")
OHQ <- read.xport("OHQ_G.XPT")
PAQ <- read.xport("PAQ_G.XPT")
PFQ <- read.xport("PFQ_G.XPT")
PUQMEC <- read.xport("PUQMEC_G.XPT")
RDQ <- read.xport("RDQ_G.XPT")
RHQ <- read.xport("RHQ_G.XPT")
RXQASA <- read.xport("RXQASA_G.XPT")
SLQ <- read.xport("SLQ_G.XPT")
SMQ <- read.xport("SMQ_G.XPT")
SMQFAM <- read.xport("SMQFAM_G.XPT")
SMQRTU <- read.xport("SMQRTU_G.XPT")
SXQ <- read.xport("SXQ_G.XPT")
TBQ <- read.xport("TBQ_G.XPT")
VTQ <- read.xport("VTQ_G.XPT")
WHQ <- read.xport("WHQ_G.XPT")
WHQMEC <- read.xport("WHQMEC_G.XPT")