library(SASxport)
ACQ<- read.xport("ACQ_J.XPT")
AUQ<- read.xport("AUQ_J.XPT")
BMX<- read.xport("BMX_J.XPT")
BPQ<- read.xport("BPQ_J.XPT")
BPX<- read.xport("BPX_J.XPT")
CDQ<- read.xport("CDQ_J.XPT")
DBQ<- read.xport("DBQ_J.XPT")
DEMO<- read.xport("DEMO_J.XPT")
DEQ<- read.xport("DEQ_J.XPT")
DIQ<- read.xport("DIQ_J.XPT")
DLQ<- read.xport("DLQ_J.XPT")
DPQ<- read.xport("DPQ_J.XPT")
AtoDPQ <- merge( DEMO, ACQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, AUQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, BMX, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, BPQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, BPX, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, CDQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, DBQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, DEMO, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, DEQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, DIQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, DLQ, by ="SEQN", all.x = TRUE)
AtoDPQ <- merge( AtoDPQ, DPQ, by ="SEQN", all.x = TRUE)
DSQIDS <- read.xport("DSQIDS_J.XPT")
DSQTOT <- read.xport("DSQTOT_J.XPT")
DUQ <- read.xport("DUQ_J.XPT")
ECQ <- read.xport("ECQ_J.XPT")
HEQ <- read.xport("HEQ_J.XPT")
HIQ <- read.xport("HIQ_J.XPT")
HSQ <- read.xport("HSQ_J.XPT")
HUQ <- read.xport("HUQ_J.XPT")
IMQ <- read.xport("IMQ_J.XPT")
KIQ <- read.xport("KIQ_U_J.XPT")
MCQ <- read.xport("MCQ_J.XPT")
OCQ <- read.xport("OCQ_J.XPT")
OHQ <- read.xport("OHQ_J.XPT")
OSQ <- read.xport("OSQ_J.XPT")
PAQ <- read.xport("PAQ_J.XPT")
PAQY <- read.xport("PAQY_J.XPT")
PFQ <- read.xport("PFQ_J.XPT")
PUQMEC <- read.xport("PUQMEC_J.XPT")
DtoP <- merge(DSQIDS, DSQTOT, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, DUQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, ECQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, HEQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, HIQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, HSQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, HUQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, IMQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, KIQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, MCQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, OCQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, OHQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, OSQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, PAQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, PAQY, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, PFQ, BY ="SEQN", all.x = TRUE)
DtoP <- merge(DtoP, PUQMEC, BY ="SEQN", all.x = TRUE)
RHQ <- read.xport("RHQ_J.XPT")
RXQRX <- read.xport("RXQ_RX_J.XPT")
RXQASA <- read.xport("RXQASA_J.XPT")
SLQ <- read.xport("SLQ_J.XPT")
SMQ <- read.xport("SMQ_J.XPT")
SMQFAM <- read.xport("SMQFAM_J.XPT")
SMQRTU <- read.xport("SMQRTU_J.XPT")
SMQSHS <- read.xport("SMQSHS_J.XPT")
WHQ <- read.xport("WHQ_J.XPT")
WHQMEC <- read.xport("WHQMEC_J.XPT")
RtoW <- merge(RXQRX, RHQ, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, RXQASA, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, SLQ, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, SMQ, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, SMQFAM, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, SMQRTU, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, SMQSHS, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, WHQ, by = "SEQN",all.x = TRUE)
RtoW <- merge(RtoW, WHQMEC, by = "SEQN",all.x = TRUE)